### ISSUE TITLE
Support Java 7 or make clear requirement on Java 8

### ISSUE THREAD

**Issue by nichtich** [slub/urnlib#1]
See <https://github.com/nichtich/urnlib/commit/ba34f368eff7f43b23303f55392c0eaf9671e11e> and <https://travis-ci.org/nichtich/urnlib/builds/110936517>

**Comment by claussni** [comment]
Nice! How about including the Travis build status and Coveralls status icons in README.md and submitting a PR?

**Comment by claussni** [comment]
I switched language level to Java 7 so this issue is resolved.
Nonetheless including tools like Travis or Coverall is worth a PR.
