### ISSUE TITLE
Make library RFC8141 compliant

### ISSUE THREAD

**Issue by buko** [slub/urnlib#10]
Please note in April 2017 the URN RFC was updated. See [RFC8141](https://tools.ietf.org/html/rfc8141). Major differences, see [Wikipedia](https://en.wikipedia.org/w/index.php?title=Uniform_Resource_Name&oldid=791661782):

> The slash character (/) is now allowed in the NSS to represent names containing slashes from non-URN identifier systems.
> The q-component was added to enable passing of parameters to named resources.
> The r-component was added to enable passing of parameters to resolvers. However, the updated specification notes that the r-component should not be used until its semantics are defined via further standardization.

**Comment by claussni** [comment]
Thanks for pointing this out! I will definitively go and check it.

**Comment by GroupThink** [comment]
This would be very helpful. Can't use the lib w/o it.

**Comment by GroupThink** [comment]
// private static final Pattern allowedCharacters = Pattern.compile("^([0-9a-zA-Z()+,-.:=@;$_!*']|(%[0-9a-fA-F]{2}))+$");
// added "/" and "&" as per RFC8141
private static final Pattern allowedCharacters = Pattern.compile("^([0-9a-zA-Z()+,/&-.:=@;$_!*']|(%[0-9a-fA-F]{2}))+$");

in NamespaceSpecificString.java

**Comment by claussni** [comment]
You can patch the code and use the library this way. Check this branch: https://github.com/slub/urnlib/tree/experiment-slash-and-ampersand

Although I would not recommend using it in production. RFC 8141 has even more differences to RFC 2141. Just allowing two characters doesn't make the library comply to RFC 8141 and violates RFC 2141. More substantial changes are coming up in another branch.

**Comment by claussni** [comment]
Work in progress at https://github.com/slub/urnlib/tree/rfc8141-compliancy

**Comment by claussni** [comment]
Work branch merged. Continuing in master...
