### ISSUE TITLE
Invalid URN hashCode implementation

### ISSUE THREAD

**Issue by PyvesB** [slub/urnlib#15]
According to the [Java specification for hashCode](https://docs.oracle.com/javase/8/docs/api/java/lang/Object.html#hashCode--):

> If two objects are equal according to the equals(Object) method, then calling the hashCode method on each of the two objects must produce the same integer result. 

This true for `URN_2141` objects but not for `URN_8141` objects. Indeed, the two following URNs are equal but produce different `hashCode`s:
```
URN.rfc8141().parse("urn:example:foo-bar-baz-qux?+CCResolve:cc=uk?=op=map#somepart"); 
URN.rfc8141().parse("urn:example:foo-bar-baz-qux");
```
This is due to the fact that `hashCode`, which calls `toString` in the current implementation, takes the RQF components into account, whereas `equals` does not.

According to [RFC 8141](https://tools.ietf.org/html/rfc8141), RQF components should not be taken into account for URN-equivalence, so I suggest changing `hashCode's implementation to reflect this. We're happy to contribute this fix! 👍

**Comment by claussni** [comment]
Thank you for spotting the issue and giving this detailed description!

Indeed, the spec says:
`If an r-component, q-component, or f-component (or any combination thereof) is included in a URN, it MUST be ignored for purposes of determining URN-equivalence.`
