### ISSUE TITLE
hexadecimal values according to RFC 4198

### ISSUE THREAD

**Issue by indika-dev** [slub/urnlib#24]
I'm using urnlib for handling URNs according to [RFC 4198](https://www.rfc-editor.org/rfc/rfc4198.html). RFC 4198 describes, that RessourceIds, part of Namespacespecific part of a URN, can be in a hexadecimal format, starting with a "%" (Chapter 3 Specification Template). Since I address the content via SHA-1 hashes, this part of the specification is relevant to me.
Typically, a FDC URN in my case looks like: `urn:fdc:127.0.0.1:20220902:%FFFF`
When I save this urn in a file via urn.toString() the result looks like: `urn:fdc:127.0.0.1:20220902:%ffFF`. It's a source of incompatibility, if these URNs are used by other tools. 
I think, urnlib detects a URL Encoded string, because of the existence of %. Could you please have a look at that?

**Comment by claussni** [comment]
Hi @indika-dev ,

thanks for the issue and sorry for the late reply. Seems my notification settings have been to strict.
This particular RFC 4198 was not in focus. I can have a look. But another RFC compatibility might require more than a quick fix.

If you can send a PR and tests, I would be happy to include the code in an appropriate release.

Regards, Ralf

**Comment by indika-dev** [comment]
Hi @claussni ,

no problem and I'll have a look into it!
