### ISSUE TITLE
Publish at maven central, jCenter or whatever is best

### ISSUE THREAD

**Issue by nichtich** [slub/urnlib#3]
Looks like maven central does not play such a central role for Java like CPAN does for Perl, npm for JavaScript or Composer for PHP but I would not like to reuse a module that is not published in such a repository.

**Comment by claussni** [comment]
Absolutely. I'm planning to publish the library in a central repository. Maven Central is still Maven default but jCenter is on the rise especially with growing relevance of Gradle.

To publish the artifact [certain requirements](http://central.sonatype.org/pages/requirements.html) like documentation and signatures have to be met. I'll keep the issue open for documenting this effort.

**Comment by claussni** [comment]
Published under http://search.maven.org/#artifactdetails|de.slub-dresden|urnlib|1.0.0|jar
