### ISSUE TITLE
URN.create method that throws an IllegalArgumentException

### ISSUE THREAD

**Issue by buko** [slub/urnlib#9]
This library is good stuff. Thank you for creating it. 🥇 

One minor issue: very often we need to define URNs as static constants in a class. Doing so isn't easy because there's no way to create a URN that doesn't raise an exception (even though we know the URN is a perfectly valid URN). There should be a method similar to [URI#create](https://docs.oracle.com/javase/8/docs/api/java/net/URI.html#create-java.lang.String-). This method should wrap the URNSyntaxException and raise an IllegalArgumentException. That would make it possible to define URNs as a static constant:

```java
 public static final URN EXAMPLE_URN = URN.create("urn:example:example");
```

**Comment by claussni** [comment]
> This library is good stuff. Thank you for creating it. :1st_place_medal:

Thanks!

URNs as static constants is an interesting use case. I think I would just implement what you described. You could also help me out by raising a pull request, though :smirk:
